[Interface]
Address = 10.90.0.5/32, fd42:42:90::5/128
PrivateKey = __WG_UPLINK_PRIVATE_KEY__
MTU = 1380
PostUp = ip link set dev %i txqueuelen 1000

[Peer]
Endpoint = REQUIRED_UPLINK_ENDPOINT:51820
PublicKey = REQUIRED_UPLINK_PUBLIC_KEY
PresharedKey = REQUIRED_UPLINK_PRESHARED_KEY
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
